### ISSUE TITLE
View Event Page

### ISSUE THREAD

**Issue by LeiSun1226** [adulbrich/osu-fsf#27]
## Background

This is a subset of: https://github.com/OregonStateUniversity/osu-fsf/issues/17

- Why do we want it? We need better engagement to improve health.
- Who is this for? OSU faculty and staff.
- Do we have data to support it? According to Nicole, there are nearly 3300 faculty and staff using the fitness app at OSU.

For other sources and data, we will get inspired by past events such as Walktober.

## Functional Requirements

- The app must display a dedicated page for each event.
- Clicking on an event on the event listing page (home page) brings the user to the event details page
- The event details page shows:
  - event description
  - event start and end dates
  - event image
  - event type (i.e., Walk)
  - participation rules
  - location (if applicable)
- The app should provide a mechanism for the participant to ask questions or contact the organizer from the event page (`mailto:`).

### Non-Functional

- Response time is under 2 seconds to load view; if tokens need to be calculated, we should display a placeholder/spinner until it shows and not slow the view

## Design Resources

[Figma](https://www.figma.com/proto/47YJ1KtmES10TIdGPuF6EZ/OSU-Fitness-App?type=design&node-id=15-11&t=mlf1vg3oCJtDB2Qa-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=151%3A290&show-proto-sidebar=1&mode=design)

## Dependencies

- Are we waiting on other user stories or tasks to complete? (blocked by) 
  - The view of past, current, and future events on the home/event listing page needs to be created.
  - The database schema needs to be initialized and mock data should be present.
  - Figure out how to manage tokens.
- Are other user stories or tasks waiting on this issue to complete? (blocking) 
  - Showing the leaderboard of all other teams.

## Tasks

- [x] Design the layout for the event information page - 3 hours
- [x] Develop navigation and routing within the app to handle viewing different events - 5 hours
- [x] Implement the event page UI in the app - 5 hours
- [x] Fetch and display event details from the backend - 3 hours
- [x] (stretch) Cache event details so that the event can load offline - 3 hours
- [x] Test the display of event information for completeness and accuracy - 1 hour

## Estimate

17 hours + (stretch) 3 hours

## Acceptance Criteria

**Given** I am using the app,
**When** I select an event to view its details,
**Then** I should be presented with a page that includes all the information I need to know to plan my participation in the event.

**Given** I am looking for specific information about the event,
**When** I browse the event page,
**Then** I should be able to easily find the information I'm looking for due to the clear organization and readability of the page.

(Stretch)
**Given** I am in a location with a slower internet connection,
**When** I access the event page,
**Then** the page should still load quickly, ensuring I can access the information without a long wait.

**Comment by adulbrich** [comment]
- After we figure out the schema for tokens, we will also see, instead of steps:
  - number of tokens (i.e., leaves) of the current user
  - number of tokens (i.e., leaves) of other team members
  - number of tokens (i.e., leaves) of the whole team
  - daily progress for earning tokens (i.e., leaves)
