### ISSUE TITLE
Join an Event

### ISSUE THREAD

**Issue by adulbrich** [adulbrich/osu-fsf#40]
We haven't figured out yet how to map the registrations on IdealLogic's platform with this platform. We might present available/current events anyway and allow people to join, but "unlock" all features only when they are identified as being registered on the other service.

Part of Epic 2 of #17

## Functional Requirements

- The app must present a list of available events.
- Participants must be able to select an event and register for it.

## Non-Functional Requirements:

- The event joining process should be intuitive and not take more than 3 steps.
- The registration for an event should be completed within 5 seconds under normal network conditions.

## Dependencies

- Supabase database with an `Events` table and participant registration functionality.
- Event information must be pre-loaded into the system.

## Tasks

- [x] Display a list of available events within the app - 4 hours
- [x] Implement the registration functionality on the UI - 4 hours
- [x] Integrate registration with Supabase - 5 hours
- [ ] Show a visual indicator that the user is registered with the event (both on the event listing and on the event itself) - 3 hours
- [x] Test the event registration process - 1 hour

## Estimate

20 hours

## Acceptance Criteria

**Given** I am interested in participating in an event,
**When** I select the event,
**Then** I should be able to register and receive confirmation of my participation.
