### ISSUE TITLE
View Step Count Leaderboard (Global)

### ISSUE THREAD

**Issue by adulbrich** [adulbrich/osu-fsf#43]
This is the global leaderboard. Users can see how their team fare against all the other teams.

Part of Epic 2 of #17 

## Functional Requirements

- The app must display a leaderboard of step counts for each team in the current event.
- The leaderboard should update regularly to reflect the most current step counts.
- Participants should be able to access the leaderboard easily from within the app.

## Non-Functional Requirements

- The leaderboard should be visually engaging and promote healthy competition.
- Step count data should be displayed in real-time or near real-time.

## Dependencies

- Supabase database with step data and functionality to rank step counts and compute total number of steps for a team.

## Tasks

- [ ] Design the UI for the step count leaderboard - 4 hours
- [ ] Implement the leaderboard functionality in the app - 6 hours
- [ ] Retrieve and display ranked step data from Supabase - 3 hours
- [ ] Test the leaderboard for accuracy and performance - 1 hour

## Estimate

14 hours

## Acceptance Criteria

**Given** I am using the app in the current event,
**When** I view the global leaderboard for all team participating in the event,
**Then** I should see where my team ranks in terms of step count for the event.

**Comment by chungyu1108** [comment]
check
