### ISSUE TITLE
Profile Page(Moblie)

### ISSUE THREAD

**Issue by chungyu1108** [adulbrich/osu-fsf#65]
Bakground
This is the profile page. Users can see the information registered in the app.

Functional Requirements
The app must display a profile page for users to view their personal information.
Participants should be able to access the page to edit the name and information within the app.

Non-Functional Requirements
The profile page should be viewed as personal information in order.

Dependencies
Supabase database with person-information data will be viewed and update.

Tasks

 Design the UI for the profile page - 4 hours
 Implement the edit function for photo and personal information - 4 hours
 Retrieve and display user data from Supabase - 4 hours
Estimate
12 hours

Acceptance Criteria
Given that I am using the app as a participant,
When I view the leaderboard, I can see myself in the event.
Then I should see where my information is in the app.

**Comment by chungyu1108** [comment]
**Bakground**
This is the profile page. Users can see the information registered in the app.

**Functional Requirements**
The app must display a profile page for users to view their personal information.
Participants should be able to access the page to edit the name and information within the app.

**Non-Functional Requirements**
The profile page should be viewed as personal information in order.

**Dependencies**
Supabase database with person-information data will be viewed and update.

**Tasks**
- [x]  Design the UI for the profile page - 4 hours
- [ ]  Implement the edit function for photo and personal information - 4 hours
- [ ]  Retrieve and display user data from Supabase - 4 hours

Estimate
12 hours

**Acceptance Criteria**
Given that I am using the app as a participant,
When I view the leaderboard, I can see myself in the event.
Then I should see where my information is in the app.

**Comment by chungyu1108** [comment]
transfer and done
