### ISSUE TITLE
View Event (web)

### ISSUE THREAD

**Issue by remingtr** [adulbrich/osu-fsf#71]
**Bakground**
The view event page will allow organizers to view past, previous, and current events.  Clicking on the event cards will take the user to a page where they can view information about an event and edit the event.  The user will also be able to search events.

**Functional Requirements**
- Clicking on an event card should redirect to a page that shows information about the event
- User should be able to click "see more" to redirect them to a page that shows the list of events
- Upcoming events should show future events, past events shows 2 of the previous events, and current event shows the current event
- Typing the name of an event in the search bar should direct the user to a page with information about the event

**Non-Functional Requirements**
- The design should be properly aligned for any screen size
- Event cards should be the same size
- Searching takes less than 1 second

**Dependencies**
Postgres must have dummy data for events
"Event Card Info" page should already be completed

**Tasks**
- [x]  Design the UI for the view event page - 6 hours
- [x]  Implement search bar functionality - 6 hours
- [x]  Implement event card clicking - 3 hours
- [x] Display event data from database onto the event cards - 6 hours

Estimate
19 hours

**Acceptance Criteria**
- The user can view more information about an event by clicking on an event
- The event cards show current data for events
- The user can search for a specific event in the search bar

**Comment by chungyu1108** [comment]
check
