### ISSUE TITLE
View All Events (web)

### ISSUE THREAD

**Issue by remingtr** [adulbrich/osu-fsf#73]
**Bakground**
Event organizers need a way to view all events for a particular category.  The View Event page shows a brief list of events, but the View All Events page will show all events for a category (e.g. past events).  The list of events will be paginated and there will be a back button to return to the view events page.  

**Functional Requirements**
- All events for a category are displayed in a paginated form
- Event cards use data from database
- User should be able to navigate to a different page by clicking the next page
- Clicking on an event card will display more information about an event

**Non-Functional Requirements**
- The results should take less than 2 seconds to load
- Switching to the next page of results should take less than 2 seconds
- Event cards are aligned properly on any screen size

**Dependencies**
"View Events" and "Detailed Event" pages should be complete
Dummy data for event cards must be in database

**Tasks**
- [x]  Design the UI for the view all events page - 3 hours
- [ ]  Implement event card clicking functionality -3 hours
- [x] Use live data from database for event cards - 5 hours
- [x] Implement pagination -1 hour
- [x] Implement back button - 30 minutes

Estimate
12 hours

**Acceptance Criteria**
- Design closely follows the figma designs
- Everything is aligned properly for any screen size
- Clicking on an event redirects to page showing more information
- Back button works properly
- Pagination works

**Comment by chungyu1108** [comment]
check
