### ISSUE TITLE
Reusable Team View (Mobile)

### ISSUE THREAD

**Issue by remingtr** [adulbrich/osu-fsf#94]
### Background

The reusable team view is a component that allows users to view a team's information and navigate to the team's page. This page is navigatable by clicking on a team card from the team list view. The team view will display the team's name, members, and total steps.  

### Requirements

- The team view should display the team's name, members, and total steps.
- The team view should be navigatable by clicking on a team card from the team list view.

### Implementation

The team view is implemented as a React component that takes in a team object as a prop. The team object contains the team's name, members, and total steps. The team view component renders the team's name, members, and total steps in a card format. The team view component also includes a link to the team's page, which is navigatable by clicking on the team card.

### Assumptions

- The team object contains the following properties:
  - `name`: The team's name.
  - `members`: An array of team members.
  - `totalSteps`: The total number of steps taken by the team.
- The team list view is already implemented and displays a list of team cards (This is not the case in this project so far, but it is assumed for the purpose of this task.)

### Tasks

- [x] Create the inital design for the team view component in figma
- [ ] Implement the design in React Native
- [ ] Use the object passed into the view component to display the team's name, members, and total steps
- [ ] Create a back button to navigate back to the team list view

**Comment by chungyu1108** [comment]
done
